apiVersion: v1
kind: ConfigMap
metadata:
  name: client-db-init
  namespace: exbanka
data:
  schema.sql: |
    CREATE TABLE clients (
        id            BIGSERIAL PRIMARY KEY,
        first_name    VARCHAR     NOT NULL,
        last_name     VARCHAR     NOT NULL,
        jmbg          VARCHAR(13) NOT NULL UNIQUE,
        date_of_birth DATE        NOT NULL,
        gender        VARCHAR     NOT NULL,
        email         VARCHAR     NOT NULL UNIQUE,
        phone_number  VARCHAR     NOT NULL,
        address       VARCHAR     NOT NULL,
        username      VARCHAR     NOT NULL UNIQUE,
        password      VARCHAR,
        active        BOOLEAN     NOT NULL DEFAULT false
    );

    INSERT INTO clients (first_name, last_name, jmbg, date_of_birth, gender, email, phone_number, address, username, password, active)
    SELECT 'Tara', 'Dunjic', '2809002785018', '2002-09-28', 'F', 'ddimitrijevi822rn@raf.rs', '+381601234567', 'Bulevar oslobodjenja 1, Beograd', 'ddimitrijevi822rn', '$2a$10$KZiA1q9EmV1PlRI0/m7i7e8a2GgitlGORbgHEbb9Y9ZUNYpxyfY.u', true
    WHERE NOT EXISTS (SELECT 1 FROM clients WHERE email = 'ddimitrijevi822rn@raf.rs');
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client-db
  namespace: exbanka
spec:
  selector:
    matchLabels:
      app: client-db
  serviceName: client-db
  replicas: 1
  template:
    metadata:
      labels:
        app: client-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: client-db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: client-db-password
            - name: POSTGRES_DB
              value: client_db
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "client_user", "-d", "client_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: client-db-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: client-db
  namespace: exbanka
spec:
  selector:
    app: client-db
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
