apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exbanka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/raf-si-2025/exbanka-4-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: API_URL
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: exbanka
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
