apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: exbanka-4
data:
  EMPLOYEE_SERVICE_ADDR: "employee-service:50051"
  AUTH_SERVICE_ADDR: "auth-service:50052"
  EMAIL_SERVICE_ADDR: "email-service:50053"
  ACCOUNT_SERVICE_ADDR: "account-service:50054"
  PAYMENT_SERVICE_ADDR: "payment-service:50055"
  CLIENT_SERVICE_ADDR: "client-service:50056"
  EXCHANGE_SERVICE_ADDR: "exchange-service:50057"
  LOAN_SERVICE_ADDR: "loan-service:50058"
  CARD_SERVICE_ADDR: "card-service:50059"
  SECURITIES_SERVICE_ADDR: "securities-service:50060"
  ORDER_SERVICE_ADDR: "order-service:50061"
  PORTFOLIO_SERVICE_ADDR: "portfolio-service:50062"
  OTC_SERVICE_ADDR: "otc-service:50063"
  FUND_SERVICE_ADDR: "fund-service:50064"
  FRONTEND_URL: "https://exbanka-4.radenkovic.rs"
  API_URL: "https://exbanka-4.radenkovic.rs/api"
  REDIS_ADDR: "redis:6379"
  OWN_ROUTING_NUMBER: "888"
  PARTNER_ROUTING_NUMBER: "333"
  PARTNER_BANK_NAME: "EXBanka 3"
  PARTNER_BANK_URL: "https://exbanka-3.radenkovic.rs/api"
  PARTNER_API_KEY: "ek_exbanka3_ad87ffa57e45d17f9f5013e750f5f397e07feef3ebe560dd"
  OWN_INTERBANK_API_KEY: "ek_exbanka4_1c715bd146a3ef672b6519349dc3419b2c37f875be0cc10c"
