apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: exbanka
data:
  EMPLOYEE_SERVICE_ADDR: "employee-service:50051"
  AUTH_SERVICE_ADDR: "auth-service:50052"
  EMAIL_SERVICE_ADDR: "email-service:50053"
  ACCOUNT_SERVICE_ADDR: "account-service:50054"
  PAYMENT_SERVICE_ADDR: "payment-service:50055"
  CLIENT_SERVICE_ADDR: "client-service:50056"
  EXCHANGE_SERVICE_ADDR: "exchange-service:50057"
  LOAN_SERVICE_ADDR: "loan-service:50058"
  CARD_SERVICE_ADDR: "card-service:50059"
  SECURITIES_SERVICE_ADDR: "securities-service:50060"
  ORDER_SERVICE_ADDR: "order-service:50061"
  PORTFOLIO_SERVICE_ADDR: "portfolio-service:50062"
  OTC_SERVICE_ADDR: "otc-service:50063"
  FUND_SERVICE_ADDR: "fund-service:50064"
  FRONTEND_URL: "http://frontend"
  API_URL: "https://changeme.example.com/api-gateway"
