apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: exbanka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: ghcr.io/raf-si-2025/exbanka-4-backend/email-service:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FROM_EMAIL
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: exbanka
spec:
  selector:
    app: email-service
  ports:
    - port: 50053
      targetPort: 50053
