apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: exbanka-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/raf-si-2025/exbanka-4-backend/payment-service:latest
          imagePullPolicy: Always
          env:
            - name: PAYMENT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: exbanka-db-pguser-payment-user
                  key: uri
            - name: ACCOUNT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: exbanka-db-pguser-account-user
                  key: uri
            - name: EXCHANGE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: exbanka-db-pguser-exchange-user
                  key: uri
            - name: CLIENT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: exbanka-db-pguser-client-user
                  key: uri
            - name: OWN_ROUTING_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: OWN_ROUTING_NUMBER
            - name: PARTNER_ROUTING_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PARTNER_ROUTING_NUMBER
            - name: PARTNER_BANK_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PARTNER_BANK_NAME
            - name: PARTNER_BANK_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PARTNER_BANK_URL
            - name: PARTNER_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PARTNER_API_KEY
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 50055
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: exbanka-4
spec:
  selector:
    app: payment-service
  ports:
    - port: 50055
      targetPort: 50055
