apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-service
  namespace: exbanka-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-service
  template:
    metadata:
      labels:
        app: securities-service
    spec:
      containers:
        - name: securities-service
          image: ghcr.io/raf-si-2025/exbanka-4-backend/securities-service:latest
          imagePullPolicy: Always
          env:
            - name: SECURITIES_DB_URL
              valueFrom:
                secretKeyRef:
                  name: exbanka-db-pguser-securities-user
                  key: uri
            - name: EMPLOYEE_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: EMPLOYEE_SERVICE_ADDR
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ALPACA_API_SECRET_KEY
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ALPHAVANTAGE_API_KEY
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: REDIS_ADDR
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 50060
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: securities-service
  namespace: exbanka-4
spec:
  selector:
    app: securities-service
  ports:
    - port: 50060
      targetPort: 50060
